name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goarch: amd64
            goos: linux
          - goarch: amd64
            goos: windows
          - goarch: arm64
            goos: linux
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: make build GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }}
